name: HTML CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}/html-sample:latest .

      - name: Test Docker image
        run: docker run --rm ghcr.io/${{ github.repository }}/html-sample:latest /bin/sh -c "echo 'HTML file exists' && test -f /usr/share/nginx/html/index.html"

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker image to GHCR
        run: docker push ghcr.io/${{ github.repository }}/html-sample:latest


      - name: Log in to Docker Hub
        run: echo "${{ secrets.dockertoken }}" | docker login -u krishnadevsecops --password-stdin

      - name: Tag Docker image
        run: docker tag your_dockerhub_username/html-sample krishnadevsecops/html-sample:latest
